eureka:
  instance:
    hostname: localhost
server:
  port: 9000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: user-service
        uri:
          lb://user-service
        predicates:
        - Path=/user/**
      - id: contact-service
        uri:
          lb://contact-service
        predicates:
        - Path=/contact/**
